### ISSUE TITLE
我按照文档配置了环境，可是按快捷键时，出现ImportError: No module named requests.auth

### ISSUE THREAD

**Issue by ghost** [tiann/markdown-img-upload#11]
首先requests模块应该安装的没问题，因为我在python命令下载执行from requests.auth import AuthBase是可以导入的，没报错

完整错误信息如下：

```
[ERROR: action.script] Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "upload.py", line 4, in <module>
    from qiniu import Auth, put_file
  File "qiniu/__init__.py", line 14, in <module>
    from .auth import Auth
  File "qiniu/auth.py", line 7, in <module>
    from requests.auth import AuthBase
ImportError: No module named requests.auth
```

但是手动执行upload.py没有任何错误，同时也没有上传剪贴板的图片，希望能给看看这是什么问题，谢了

**Comment by tiann** [comment]
用的python是3.x吗？

**Comment by 16bh** [comment]
完美的方法，我最近的博客图片都这样切换到七牛了，如果mac上安装request库没成功可以参考这个：https://16bh.github.io/default/python%E5%AE%89%E8%A3%85requests%E5%BA%93/

**Comment by tiann** [comment]
@16bh 链接404了

**Comment by 16bh** [comment]
@tiann  https://16bh.github.io/2016/07/07/python%E5%AE%89%E8%A3%85requests%E5%BA%93/

**Comment by tiann** [comment]
@16bh thank you! good job!!
@lifengsofts 试试楼上给出的方法 ^_^
