### ISSUE TITLE
[2016-06-23 18:02:01][trigger.hotkey] Processing output of 'action.script' with arg '' 提示上传图片到图床失败

### ISSUE THREAD

**Issue by bingofly** [tiann/markdown-img-upload#12]
[2016-06-23 18:02:01][trigger.hotkey] Processing output of 'action.script' with arg '' 提示上传图片到图床失败

3.02 alfred版本.

**Comment by tiann** [comment]
暂不支持 3.x版本。

**Comment by bingofly** [comment]
晴天霹雳 刚买正版.

**Comment by bingofly** [comment]
有机会支持么,是哪里需要修改.

**Comment by tiann** [comment]
我自己没有3.0版本，所以不知道哪里改了；如果可以的话，你可以看我的源码，自己调试一下。

**Comment by bingofly** [comment]
你的workflow是支持  3.0以上版本

我在自己用官方python demo的时候发现 bucket 改为华东地区就可以了.
太......

**Comment by tiann** [comment]
good job!

**Comment by bingofly** [comment]
谢谢 你开发这么棒的工具
