### ISSUE TITLE
你好，我在mac OS X 10.11.16版本中报错，下面是debug信息

### ISSUE THREAD

**Issue by yzhfd** [tiann/markdown-img-upload#17]
[2017-01-09 10:12:24][ERROR: action.script] Traceback (most recent call last):
  File "<string>", line 22, in <module>
TypeError: 'NoneType' object is not iterable

**Comment by tiann** [comment]
@yzhfd 具体是如何操作的呢？哪一步出现这个错误？

**Comment by hiberabyss** [comment]
@tiann 在 Alfred workflow 的 debug 窗口可以看到这个信息。当把 bucket 的地区从华北改到了华东就没有这个错误提示了。

**Comment by tiann** [comment]
@hiberabyss 多谢指出，可能是我qiniu SDK版本有点低；
@yzhfd 可以试试楼上说的这种解法是否正确，已经有两人反馈这个问题了，应该是靠谱的，问题先关闭了。
