### ISSUE TITLE
jpg图片被更改为png

### ISSUE THREAD

**Issue by xiaomaisu** [tiann/markdown-img-upload#18]
clipboard.py把拷贝的jpg图片强制性转换成了png图片，不知道出于什么考虑，可以去掉covert_to_png吧

**Comment by tiann** [comment]
@xiaomaisu 是因为QQ，微信等软件截图的格式是tiff，这种格式的图片非常大，经常有数兆；压缩的时候使用的tinypng，但是这玩意儿不支持tiff，因此为了方便，把所有格式全转成了png。并非针对jpg的，如果不满足你的需求，可以自己修改。
