### ISSUE TITLE
按下快捷键后，粘贴出两个url链接啦

### ISSUE THREAD

**Issue by lxzh123** [tiann/markdown-img-upload#19]
<img src="http://o8ydbqznc.bkt.clouddn.com/markdown/1486909937643.png" width="302"/>
如上图所示，在编辑器里按了快捷键后为嘛会出现两个结果呢

**Comment by tiann** [comment]
是不是手速太快了。。。

**Comment by lxzh** [comment]
不是，好多次都这样~

**Comment by tiann** [comment]
什么编辑器，是不是对ctrl的处理不好？可以换个快捷键， 不用 cmd + ctrl + V，避免跟 cmd + v混淆了。

**Comment by lxzh** [comment]
与编辑器无关，试了几个地方哦~快捷键也换了，换成cmd+ctrl+s还是一毛样，索性把
#os.system('osascript -e \'tell application "System Events" to keystroke "v" using command down\'')
这行注释后就没问题了，上传后再按cmd+v粘贴

**Comment by tiann** [comment]
多按了几次吧。。上传是同步的，会等一两秒才出来，这时候你再按就重复了

**Comment by lxzh** [comment]
毛啊，试了N次都是这种问题，哥会犯这种低级错误嘛~
这里肯定有某种bug，只是你那里复现不出来罢了~
丫的，居然把问题给close啦~

**Comment by tiann** [comment]
这个问题我这里复现不了，而且你已经解决掉了啊；只能close啦 : ) 如果你有精力能找到具体是哪里的问题就更好了

**Comment by zwmmm** [comment]
我也遇到了这个问题 但是的情况是不会自动粘贴 需要手动粘贴
