### ISSUE TITLE
alfred debug模式下报错

### ISSUE THREAD

**Issue by lebensterben** [tiann/markdown-img-upload#2]
[ERROR: alfred.workflow.action.script] Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "upload.py", line 4, in <module>
    from qiniu import Auth, put_file
  File "qiniu/**init**.py", line 14, in <module>
    from .auth import Auth
  File "qiniu/auth.py", line 7, in <module>
    from requests.auth import AuthBase
ImportError: No module named requests.auth

**Comment by tiann** [comment]
需要安装requests这个库；pip 或者easy_install即可。

**Comment by lebensterben** [comment]
pip install requests 成功了，出现同样的错误。。

**Comment by tiann** [comment]
1. python3？
2. 重新加载一遍这个拓展

**Comment by lebensterben** [comment]
Python 2.7.11
我不知道如何重新加载。。我尝试退出alfred重启，还是一样的报错

**Comment by tiann** [comment]
在命令行输入python进入解释器环境，输入：
from requests.auth import AuthBase

这个会报错吗？

**Comment by lebensterben** [comment]
不报错

**Comment by tiann** [comment]
1. pip show requests 查看一下安装的requests在哪里
2. 查看第一步requests目录的权限是什么，如果权限问题，可能需要重新装；

实在不行，我就把这个requests也打包到这个项目里面吧。

**Comment by lebensterben** [comment]
权限是 drwxr-xr-x  我感觉问题出在我自己这里。。

**Comment by tiann** [comment]
不科学啊，难道你当前不是管理员用户；Mac 10.11系统吗？具体requests是安装在哪里？

**Comment by lebensterben** [comment]
我是管理员，是10.11，安装目录是/usr/local/lib/python2.7/site-packages

**Comment by tiann** [comment]
10.11的权限问题；我把这个库打包，稍等。

**Comment by tiann** [comment]
@lebensterben 依赖有点多，不太好打包；你安装的时候，是直接
`sudo pip install requests`吗？
是不是出现一堆警告建议用
`sudo -H pip install requests`

**Comment by lebensterben** [comment]
我都没有用sudo。。。没有任何警告

**Comment by lebensterben** [comment]
我卸载了，然后用sudo pip install requests，的确它建议我加-H参数

**Comment by tiann** [comment]
重新使用 `sudo -H pip install requests`安装试试

**Comment by lebensterben** [comment]
报同样地错。。

**Comment by tiann** [comment]
这样，你把requests安装在alfred那个插件的本地目录吧，跟upload.py同级：

`pip install --target . requests`

**Comment by lebensterben** [comment]
我打算放弃了……

Lucius

**Comment by tiann** [comment]
我这也没有10.11的机器，爱莫能助阿..别放弃治疗。

**Comment by EkkoG** [comment]
同样的问题。。我试试吧，这个方案上传图片真的挺方便的，不想放弃。。。

**Comment by EkkoG** [comment]
可以用 pip 的 -t 参数把 `requests` 安装到 qiniu 目录中
如果遇到 `distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both` 错误，可以按照这个方法解决
https://stackoverflow.com/questions/24257803/distutilsoptionerror-must-supply-either-home-or-prefix-exec-prefix-not-both
已成功

**Comment by tiann** [comment]
@cielpy 棒棒嗒～
@lebensterben 问题已经解决，试试看？

**Comment by lebensterben** [comment]
找不到qiniu目录..请问在哪

**Comment by EkkoG** [comment]
在 Workflows 里找到相应的 workflow 然后右键 show in Finder 就看到了

-- 
Kevin Guo
Sent with Airmail

在 2016年4月16日 下午2:32:02, Lucius Hu (notifications@github.com) 写到:

找不到qiniu目录..请问在哪

**Comment by EkkoG** [comment]
按照 https://stackoverflow.com/questions/24257803/distutilsoptionerror-must-supply-either-home-or-prefix-exec-prefix-not-both 的解决方法会有后遗症，该解决方案将 pip 的路径前缀设置为空， 用 brew 安装的 pip 的默认路径前缀是 /usr/local，正常安装的话会将 module 安装到 /usr/local/lib/xxx 下，如果设置为空，再用 pip 安装全局的  module 的话会安装到 /lib/xxx 下，需要 root 权限

**Comment by tiann** [comment]
@cielpy 👍
