### ISSUE TITLE
我想问下 不能看到 md 中的预览图吗?

### ISSUE THREAD

**Issue by tutuoo** [tiann/markdown-img-upload#21]
~~~

**Comment by tiann** [comment]
能否看到预览图，跟md编辑器相关；可能是这个编辑器不支持<img>标签？

**Comment by tutuoo** [comment]
<img src="opmmds7g1.bkt.clouddn.com/md/1494247226555.png" width="36"/>

**Comment by tutuoo** [comment]
< img src="opmmds7g1.bkt.clouddn.com/md/1494247226555.png" width="36" />
我这边复制出来的是这样的   但是我看您 Demo 上是 http 打头的  
后来我去七牛那边的图上  看到复制外链的链接  拿到我的编辑器上面 可以看到图. 
是我哪里的配置出问题了吗?

**Comment by tiann** [comment]
@tutuoo 你的配置config.ini 里面的那个url，是需要带http:// 前缀的，你检查一下是不是没有

**Comment by tutuoo** [comment]
是的,我现在加上去了, 但是按照前面那个还是不行  我把前面两行注释掉 可以看到图 但是图片会放大
```
#     markdown_url = '<img src="%s/%s" width="%d"/>' % (url, upload_name, size)
# else:
        markdown_url = '%s/%s' % (url, upload_name)
```

**Comment by tiann** [comment]
嗯，之所以用img标签，就是处理retina屏幕截图变大的。
你加上url配置之后，粘贴出现的东西是什么？

**Comment by tutuoo** [comment]
`<img src="http://opmmds7g1.bkt.clouddn.com/md/1494247879191.png" width="164"/>`

**Comment by tutuoo** [comment]
我发现现在复制不出来了.. 这个是我之前复制出来的

**Comment by tiann** [comment]
这个链接对应的图片是有效的；你的md编辑器是什么？应该是它不支持img标签。

Github的md编辑器是支持的，比如：
<img src="http://opmmds7g1.bkt.clouddn.com/md/1494247879191.png" width="164"/>

**Comment by tutuoo** [comment]
编辑器是 mWeb

**Comment by tutuoo** [comment]
现在我复制不出来了  七牛上面也没有图    窗口也没有提示

**Comment by tutuoo** [comment]
好啦好啦,谢谢,我重新配置了一下 可以看到图啦~~

**Comment by tiann** [comment]
: )
