### ISSUE TITLE
剪切板里没有图片

### ISSUE THREAD

**Issue by sivan67** [tiann/markdown-img-upload#4]
按照步骤修改了 config.ini 里面的内容，在 MacDown 里使用快捷键粘贴的时候提示剪切板里 没有图片

**Comment by tiann** [comment]
是截图，复制本地图片还是复制链接？
如果是截图和本地图片，是什么格式？

**Comment by sivan67** [comment]
就是系统截图 .png 格式的

**Comment by sivan67** [comment]
clipboard需要导入什么包吗，没用过Python语言，截图、复制本地图片和复制链接都是提示剪切板里没有图片

**Comment by tiann** [comment]
clipboard用的类理论上是系统有的；你用Alfred的debug模式运行，然后把日志贴出来一下。

**Comment by tiann** [comment]
![image](https://cloud.githubusercontent.com/assets/4233744/13546671/37369dee-e2f0-11e5-8e13-572f18db0df4.png)

**Comment by sivan67** [comment]
[INFO: alfred.workflow.trigger.hotkey] Processing output 'alfred.workflow.action.script' with arg ''

**Comment by tiann** [comment]
日志信息那里选择 All Information, 在看看有没有别的日志？

**Comment by sivan67** [comment]
这个就是 All Information 了

**Comment by tiann** [comment]
@sivan67 我重新导出了一个工作流文件，在根目录；你试一下这个，然后有问题看看日志是什么

**Comment by sivan67** [comment]
![](http://7xrk97.com1.z0.glb.clouddn.com/16-3-5/3346830.jpg)

**Comment by tiann** [comment]
截图，Ctrl + cmd + V；然后cmd + V能得到链接吗？

**Comment by sivan67** [comment]
截图不可以，复制本地图片可以，但链接不是 Markdown 格式的，只是单纯的图片地址链接

**Comment by tiann** [comment]
嗯，本地图片不是markdown格式的；因为截图retina屏幕有特殊处理；本地图片不知道是何种格式；

至于截图不行的问题，那么，系统是什么版本的？

**Comment by sivan67** [comment]
10.11.3

**Comment by tiann** [comment]
我不确定10.11 系统对截图API有没有修改，我找个虚拟机试一下。

**Comment by sivan67** [comment]
系统截图完成之后会将图片存在剪切板上吗？我这里貌似没有

**Comment by tiann** [comment]
你是通过什么快捷键截图？cmd + shift + ctrl + 4?  还是cmd + shift + 4

**Comment by sivan67** [comment]
额，是cmd + shift + 4，刚刚测试qq截图好用，cmd + shift  + ctrl + 4 也好用

**Comment by sivan67** [comment]
感谢。不过我想再请教一下，我是 air，修改那个地方可以使用 Markdown 格式

**Comment by tiann** [comment]
^_^   cmd + shift + 4 会存文件到桌面，加上ctrl 就会放在剪切版里面；这样，你用cmd + v就能粘贴图片了

#close

**Comment by tiann** [comment]
^_^  cmd + shift + 4 是把图片放桌面；加上ctrl是放在剪切版里面；

如果想把本地图片也改成markdown格式，修改info.plist, 把第112行修改为：

`markdown_url = '![%s/%s]()' % (url, upload_name)`

**Comment by tiann** [comment]
@sivan67 兄弟，给个star?

**Comment by sivan67** [comment]
好的，非常感谢
