### ISSUE TITLE
无效,没有任何错误提示

### ISSUE THREAD

**Issue by luckydarcy** [tiann/markdown-img-upload#6]
装好了以后,我自定义了快捷键,发现什么都没有发生,然后又定义了热键,也没有作用.
求看下~

**Comment by tiann** [comment]
是截图之后按热键吗？截图用的什么快捷键？

**Comment by luckydarcy** [comment]
截图或者是右键复制一个图片再激活功能都没有反应.
ps:我修改了 pass through to workflow 为 show alfred . 然后使用热键alfred是被呼出了,说明确实这个动作是激活了.

**Comment by tiann** [comment]
![image](https://cloud.githubusercontent.com/assets/4233744/13842050/33b76772-ec67-11e5-9065-3e1053f2de7e.png)
点击这个蚂蚁，开debug看看日志？

**Comment by luckydarcy** [comment]
[INFO: alfred.workflow.trigger.hotkey] Processing output 'alfred.workflow.action.script' with arg ''
谢啦~

**Comment by tiann** [comment]
你的快捷键是什么？

**Comment by luckydarcy** [comment]
![e57a6e42-d4df-404f-8c33-b9be37acf0d6](https://cloud.githubusercontent.com/assets/7982062/13842216/fdd76f3e-ec67-11e5-991b-8d1650d6f229.png)

**Comment by tiann** [comment]
有点奇怪额；你的系统版本多少？ workflow是从github上下载的吗？还有你输入mdimgsetup能弹出设置文本文件吗？

**Comment by luckydarcy** [comment]
mac   10.11.3 Beta (15D13b)
alfred 2.8.3
是从github上下载的.且我其他的workflow都是好的.
设置mdimgsetup是能够弹出设置文本的

**Comment by tiann** [comment]
正常情况下应该是会有通知栏提醒的；不知道是不是10.11的通知提醒有问题；

你在终端执行一下：

`osascript -e 'display notification "hehe" with title "hehehehe"'`

看看会不会调出mac的系统通知；

**Comment by luckydarcy** [comment]
![e07d71ca-908e-4ed2-b908-3e339c063e96](https://cloud.githubusercontent.com/assets/7982062/13842868/6fae8b94-ec6b-11e5-8911-9e288f8f698b.png)

**Comment by tiann** [comment]
1，不截图，直接使用热键 会弹出通知提醒吗？
2，截图之后按下热键；找个地方cmd + V一下，有内容吗？

**Comment by luckydarcy** [comment]
1. 没有通知
2. 没有内容

**Comment by tiann** [comment]
那个debug日志，输出的是所有信息吗？
![image](https://cloud.githubusercontent.com/assets/4233744/13843241/77cdac9a-ec6d-11e5-9838-a90101791008.png)

**Comment by luckydarcy** [comment]
之前就是 all information
我尝试出来是这样一种现象:
编辑热键对应的脚本,先将图片中的那个 dollors 打上勾,然后save,然后用热键激活下,这时候会报错,
![45ee5f3f-b122-48bc-881a-d1a03d3de7b5](https://cloud.githubusercontent.com/assets/7982062/13843867/27cb8358-ec71-11e5-8cc6-8b5e8c93c826.png)
之后再编辑热键对应的脚本,再恢复成初始状态(没有doller勾选)
![3a74c2c1-6885-466b-8bcb-91b07e1cbe8a](https://cloud.githubusercontent.com/assets/7982062/13843674/1c0ddb34-ec70-11e5-9f27-27cf41493769.png)

再激活热键,就会报错如下截图
![5f43cbec-f58c-4882-bdaa-9dc4273727db](https://cloud.githubusercontent.com/assets/7982062/13843645/e5069a9a-ec6f-11e5-9eac-26946ccc3d53.png)

**Comment by tiann** [comment]
我明白了。。。。。忘了 😓

**Comment by tiann** [comment]
需要安装requests 这个库 @8485296

**Comment by tiann** [comment]
python用pip安装

**Comment by luckydarcy** [comment]
![e5c74927-e314-4ca7-8b90-17be1500f708](https://cloud.githubusercontent.com/assets/7982062/13844387/70d7dc9c-ec74-11e5-894e-646dc8af234d.png)
装好了,这是新的报错信息

**Comment by tiann** [comment]
1，不截图，直接使用热键 会弹出通知提醒吗？
2，截图之后按下热键；找个地方cmd + V一下，有内容吗？

**Comment by luckydarcy** [comment]
1. 不截图直接使用热键,依然没有通知提醒.debug报错:
   [INFO: alfred.workflow.trigger.hotkey] Processing output 'alfred.workflow.action.script' with arg ''
   [ERROR: alfred.workflow.action.script] Traceback (most recent call last):
   File "<string>", line 21, in <module>
   TypeError: 'NoneType' object is not iterable
2. 截图之后使用了下,完美上传了!!!!!

不过我上面的问题,为什么切换了dollars 这个勾选项以后才能生效呢...好神奇啊.
总之现在可以用了,谢谢啦

**Comment by tiann** [comment]
@8485296 不截图使用热键没有通知已经确认是bug；（链接粘贴图片并没有实现的问题）

已经把注意点添加进Readme；感谢反馈！写的时间有点长，都忘了。。

那个勾选项是转义用的；理论上不需要程序里面木有$符号；不过你的Alfred版本和我的不一样；具体也不清楚。

**Comment by luckydarcy** [comment]
好的,总体来说非常方便和好用!~谢谢~

**Comment by tiann** [comment]
@8485296 谢谢 😁   不过对于使用者来说确实成本有点高；我改一下文档说明，然后尽量不要依赖！
