### ISSUE TITLE
alfred 报 global name 'png_file' is not defined 错误

### ISSUE THREAD

**Issue by deliangliao** [tiann/markdown-img-upload#9]
[ERROR: alfred.workflow.action.script] Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "clipboard.py", line 69, in get_paste_img_file
    _convert_to_png(tmp_clipboard_img_file.name, png_file.name)
NameError: global name 'png_file' is not defined

**Comment by tiann** [comment]
fixed on https://github.com/tiann/markdown-img-upload/commit/558c8836594e43dc23d982b70cf4a99ac95ac043
